import React from "react";
import BurgerMenu from "../../Components/BurgerMenu/BurgerMenu";
import Monkey from "../../assets/img/About/Monkey.png";
import Dagger from "../../assets/svg/About/dagger.svg";
import {
  Section,
  HistoryContainer,
  TitleContainer,
  MonkeyContainer,
  BurgerMenuWrapper,
  Banner,
} from "./about.styled";

const About = () => {
  return (
    <Section id="aboutSection" >
      <HistoryContainer>
        <TitleContainer>
          <h2>
            a Story that started with <span>one simple ape</span>
          </h2>
          <div>
            <img src={Dagger} alt="Dagger" />
            <p>
              EACH ARTWORK IN THE COLLECTION TELLS A STORY OF ONE JOURNEY. ARTS
              ARE RANDOMLY GENERATED BY USERS
            </p>
          </div>
        </TitleContainer>
        <MonkeyContainer>
          <p>
            WHO GOT FED UP WITH BORING AND HYPOCRITIC COMMONPLACE THIS IS HOW
            THE IDEA OF ESCAPING AND DYNAMIC JOURNEY ON THE <br /> YACHT
          </p>
          <BurgerMenuWrapper>
            <BurgerMenu textColor="#FFF" bgColor="rgba(255, 255, 255, 0.10)" />
          </BurgerMenuWrapper>
          <img src={Monkey} alt="Monkey" />
        </MonkeyContainer>
      </HistoryContainer>
 
      <Banner>
        <h2>Destroy stereotypes</h2>
        <img src={Dagger} alt="Dagger" />
        <h2>HAVE NO LIMITS</h2>
        <img src={Dagger} alt="Dagger" />
        <h2>Break rules</h2>
      </Banner>
      
    </Section>
  );
};

export default About;
